apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-app-backend
  template:
    metadata:
      labels:
        app: sample-app-backend
    spec:
      containers:
        - image: okteto.dev/sample-app-backend:latest
          name: sample-app-backend
          env:
            - name: DATABASE_URL
              value: $DATABASE_URL

---
apiVersion: v1
kind: Service
metadata:
  name: sample-app-backend
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP
  ports:
    - name: "sample-app-backend"
      port: 3001
  selector:
    app: sample-app-backend
